# Generated by Django 3.2.5 on 2021-09-10 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='buyer_status',
            new_name='status',
        ),
    ]
