# Generated by Django 3.2.5 on 2021-09-13 07:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivary_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 23, 13, 14, 51, 963035)),
        ),
    ]
