# Generated by Django 3.2.5 on 2021-08-07 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category_image_image',
            new_name='category_image',
        ),
    ]
